---
os:
  - linux
  - osx
dist: xenial
language: ruby
cache: bundler

branches:
  only:
    - /.*/

rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.2
  - jruby-9.2.0.0

env:
  - DISPLAY=":0"

addons:
  firefox: latest
  apt:
    packages:
      - ffmpeg
  homebrew:
    packages:
      - ffmpeg

before_script:
  - nohup Xvfb :0 -screen 0 1024x768x24 &